services:
  - type: web
    name: blog-leticia-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: npm_config_build_from_source
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://blog-leticia.onrender.com
