services:
  - type: web
    name: blog-leticia-api
    env: node
    region: oregon
    plan: free
    buildCommand: apt-get update && apt-get install -y build-essential python3 && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://blog-leticia.onrender.com
